name: xopr-test
channels:
  - conda-forge
dependencies:
  # Core project dependencies  
  - python>=3.10
  - numpy
  - scipy
  - xarray
  - h5netcdf
  - requests
  - matplotlib
  - aiohttp
  - geoviews
  - shapely
  - geopandas
  - h5py
  - fsspec
  - dask
  
  # Testing and code quality tools
  - pytest
  - pytest-cov
  - coverage
  - flake8
  - pytest-xdist  # parallel test execution
  - pytest-mock   # mocking support
  
  # STAC-specific dependencies (optional - for STAC functionality and testing)
  - pystac
  - pip:
    - stac_asset
    - stac_geoparquet
    - stac-validator
