name: xopr
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - xarray
  - dask
  - h5netcdf
  - h5py
  - requests
  - matplotlib
  - copier
  - hatch
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - aiohttp
  - hvplot
  - jupyter_bokeh
  - geoviews
  - geopandas
  - pystac
  - pystac_client
  - stac-geoparquet
  - shapely
  - pip
  - pip:
    - pystac_client
    - stac_asset
    - stac-fastapi-geoparquet[serve]
