[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "uv_build"]
build-backend = "setuptools.build_meta"

[project]
name = "xopr"
dynamic = ["version"]
description = "Access Open Polar Radar data in the Python data ecosystem"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "xarray",
    "h5netcdf",
    "requests",
    "matplotlib",
    "aiohttp",
    "geoviews",
    "pystac",
    "shapely",
    "geopandas",
    "h5py",
    "scipy",
    "pystac_client",
    "stac_asset",
    "fsspec"
]

[project.optional-dependencies]
stac = [
    "stac-fastapi-geoparquet[serve]",
    "stac-geoparquet",
]
docs = [
    "jupyter-book>=2.0.0a0",
    "dask[distributed]",
    "coiled>=1.117.0",
    "ipykernel",
    "hvplot",
    "jupyter_bokeh",
]


