[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "xopr"
version = "0.1.0"
description = "Access Open Polar Radar data in the Python data ecosystem"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "xarray",
    "dask",
    "h5netcdf",
    "requests",
    "matplotlib",
    "aiohttp",
    "hvplot",
    "jupyter_bokeh",
    "geoviews",
    "pystac",
    "shapely",
    "geopandas", 
    "h5py",
    "scipy",
    "pystac_client",
    "stac_asset",
    "ipykernel"
]

[project.optional-dependencies]
stac = [
    "stac-fastapi-geoparquet[serve]",
    "stac-geoparquet",
]
docs = [
    "jupyter-book>=2.0.0a0",
]


