# XOPR STAC Catalog Configuration - AWI
# =======================================
# Configuration for building STAC catalogs from AWI (Alfred Wegener Institute) radar data

version: "1.0.0"

# Data source configuration
data:
  root: "/path/to/awi/data"  # Update with actual AWI data path
  provider: "awi"  # Data provider identifier for xopr:provider metadata
  primary_product: "CSARP_standard"
  extra_products:
    - "CSARP_layer"
    - "CSARP_qlook"

  # Campaign filtering (optional)
  campaigns:
    include: []
    # Example AWI campaigns (typically Polar6 aircraft):
    # - "2016_Greenland_Polar6"
    # - "2017_Greenland_Polar6"
    # - "2018_Antarctica_Polar6"

    exclude: []

# Output configuration
output:
  path: "${pwd}/stac_catalog_awi"
  catalog_id: "OPR-AWI"
  catalog_description: "Open Polar Radar AWI airborne data from Polar6 aircraft"
  license: "various"

# Processing configuration
processing:
  n_workers: 4  # Number of parallel workers for processing
  memory_limit: "4GB"  # Memory limit per worker
  max_items: null  # Maximum items to process (null for unlimited)

# Asset configuration
assets:
  base_url: "https://example.awi.de/data/"  # Update with actual AWI data URL

# Logging configuration
logging:
  verbose: true
  level: "INFO"

# Geometry simplification configuration
geometry:
  simplify: true
  tolerance: 100.0  # Tolerance in meters for geometry simplification

# Environment-specific settings (optional)
# environments:
#   production:
#     processing:
#       n_workers: 16
#     logging:
#       verbose: false
#   development:
#     processing:
#       n_workers: 2
#     logging:
#       verbose: true
#       level: "DEBUG"