# Jupyter Book configuration

title: xopr Documentation
author: xopr Contributors

# Enable MyST extensions
parse:
  myst_enable_extensions:
    - substitution
    - html_image
    - linkify
    - colon_fence

# Global substitutions available across all documents
# These can be overridden in individual document frontmatter
substitutions:
  # Default test data
  test_pole: south
  test_parquet: |
    ['https://storage.googleapis.com/opr_test_dataset_1/test_antarctic_random_walk.parquet']
  
  # Antarctica data
  antarctica_2010_2011: |
    ['https://storage.googleapis.com/opr_stac/testing/2010_Antarctica_DC8.parquet',
     'https://storage.googleapis.com/opr_stac/testing/2011_Antarctica_DC8.parquet']
  
  # Greenland data  
  greenland_2011_2012: |
    ['https://storage.googleapis.com/opr_stac/testing/2011_Greenland_P3.parquet',
     'https://storage.googleapis.com/opr_stac/testing/2012_Greenland_P3.parquet']