name: Build and Deploy Jupyter Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write  # Added for PR comments

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BASE_URL: /xopr

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
        uv sync --extra test --extra stac
    
    - name: Install package in development mode
      run: |
        uv pip install -e .
    
    - name: Run tests with pytest
      run: |
        uv run pytest --cov=xopr --cov-report=html --cov-report=xml --cov-report=term
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./htmlcov

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --extra docs

    - name: Build Jupyter Book
      run: |
        cd docs
        uv run --extra docs jupyter-book build --html --execute 2>&1 | tee jupyter-book-build.log
        # Check for errors running the notebooks and fail if any are found
        if grep -r "Error\\|Exception\\|Traceback" jupyter-book-build.log; then
          echo "Found execution errors in build"
          exit 1
        fi

    - name: Download coverage artifacts
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: ./coverage-temp

    - name: Copy coverage to docs build
      run: |
        mkdir -p docs/_build/html/coverage
        cp -r ./coverage-temp/* docs/_build/html/coverage/
    
    # Copy map assets for polar map functionality
    - name: Copy map assets
      run: |
        if [ -d "src/xopr/map" ]; then
          echo "Copying map assets from src/xopr/map..."
          mkdir -p docs/_build/html/_static/maps
          cp -f src/xopr/map/polar.html docs/_build/html/_static/maps/ 2>/dev/null || true
          cp -f src/xopr/map/parquet_wasm.js docs/_build/html/_static/maps/ 2>/dev/null || true
          cp -f src/xopr/map/parquet_wasm_bg.wasm docs/_build/html/_static/maps/ 2>/dev/null || true
          cp -f src/xopr/map/*.parquet docs/_build/html/_static/maps/ 2>/dev/null || true
          echo "Map assets copied successfully"
        else
          echo "Warning: src/xopr/map directory not found, skipping map assets"
        fi
    
    # Upload artifact for all builds (PR and main)
    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-html-${{ github.sha }}
        path: docs/_build/html
        retention-days: 7

    - name: Setup Pages
      uses: actions/configure-pages@v5
      if: github.ref == 'refs/heads/main'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main'
      with:
        path: docs/_build/html

  # Deploy PR Preview to GitHub Pages branch
  pr-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Download docs artifact
      uses: actions/download-artifact@v4
      with:
        name: docs-html-${{ github.sha }}
        path: ./docs-preview
    
    - name: Deploy to GitHub Pages branch
      id: gh_pages_deploy
      run: |
        # Configure git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Create or checkout the PR preview branch
        PREVIEW_BRANCH="pr-preview-${{ github.event.pull_request.number }}"
        
        # Check if branch exists on remote
        if git ls-remote --heads origin $PREVIEW_BRANCH | grep -q $PREVIEW_BRANCH; then
          echo "Branch $PREVIEW_BRANCH exists, fetching and checking out"
          git fetch origin $PREVIEW_BRANCH:$PREVIEW_BRANCH
          git checkout $PREVIEW_BRANCH
        else
          echo "Creating new orphan branch $PREVIEW_BRANCH"
          git checkout --orphan $PREVIEW_BRANCH
        fi
        
        # Clean the branch
        git rm -rf . 2>/dev/null || true
        
        # Copy the built docs
        cp -r ./docs-preview/* .
        
        # Add all files
        git add -A
        
        # Commit (allow empty in case nothing changed)
        git commit -m "Deploy PR #${{ github.event.pull_request.number }} preview - commit ${{ github.sha }}" --allow-empty
        
        # Push to GitHub
        git push origin $PREVIEW_BRANCH --force
        
        # Set output for the URL
        echo "preview_url=https://thomasteisberg.github.io/xopr/pr-preview-${{ github.event.pull_request.number }}/" >> $GITHUB_OUTPUT
    
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.issue.number;
          const sha = context.sha.substring(0, 7);
          const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }}`;
          const previewUrl = '${{ steps.gh_pages_deploy.outputs.preview_url }}';
          
          let body = `## 📚 Documentation Preview Ready!\n\n`;
          
          // Add GitHub Pages preview URL
          if (previewUrl) {
            body += `### 🌐 Live Preview\n**URL:** ${previewUrl}\n\n`;
            body += `*Note: It may take a few minutes for GitHub Pages to update.*\n\n`;
          }
          
          body += `### 📦 Download Preview\n`;
          body += `You can download the preview artifact [here](${artifactUrl}) for local viewing.\n\n`;
          body += `**Commit:** \`${sha}\`\n\n`;
          body += `---\n*This preview will be updated automatically with new commits.*`;
          
          // Find and update existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber
          });
          
          const botComment = comments.find(comment => 
            comment.user.login === 'github-actions[bot]' && 
            comment.body.includes('Documentation Preview Ready')
          );
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });
          }

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4