name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv sync --extra test --extra stac
    
    - name: Install package in development mode
      run: |
        uv pip install -e .
    
    - name: Run flake8
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,build,dist,*.egg-info,.git,.pytest_cache,__pycache__
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics --exclude=.venv,build,dist,*.egg-info,.git,.pytest_cache,__pycache__
    
    - name: Run tests with pytest
      run: |
        uv run pytest --cov=xopr --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
